### ISSUE TITLE
Support for UE 4.14

### ISSUE THREAD

**Issue by saidmoya12** [EverNewJoy/VictoryPlugin#16]
Could you add support for UE4.14

Thanks

**Comment by EverNewJoy** [comment]
the latest version is running on 4.14 :)

**Comment by saidmoya12** [comment]
Thanks for you answer but I test the last version just yesterday. **(05-01-2016)**

And I recived this message:
Missing or incompatible modules in Victory BPLibrary plugin - would you like disable it?

I need do something first??

Again, thanks for your help.

**Comment by EverNewJoy** [comment]
That's odd, I tested the version I uploaded just now in 4.14 and it is working fine, I am still on 4.14.0 but I that shouldn't matter since hotfixes are always binary compatible. That's the only possible thing I could imagine but then I'd think lots of ppl would be reporting this matter.

Will update my engine version and let you know if anything comes of it, otherwise please continue your own investigation.

Rama

**Comment by EverNewJoy** [comment]
I just upgraded to 4.14.2 and the latest version of Victory Plugin runs fine for me :)

Latest version is here, 12-30-16

http://www.mediafire.com/file/ieovbd5l9d7yub2/VictoryPlugin.zip
