### ISSUE TITLE
"Joy File IO Get Files"  doesn't work

### ISSUE THREAD

**Issue by jusakurai** [EverNewJoy/VictoryPlugin#34]
Hi Rama,

I am trying plugin 4.17.  But "Joy File IO Get Files"  doesn't work in it.
Please advice this issue.

**Comment by campmdabt** [comment]
The update from this commit (https://github.com/EverNewJoy/VictoryPlugin/commit/212ad2dcda5bfc993a357737eede402140187c47) seems like it should be good for error checking, but it fails even with an absolute path that exists, so I had to remove it. Didn't have time to setup a good pull request or dig deeper yet though.

**Comment by EverNewJoy** [comment]
@campmdabt 

Thank you for pointing that out!

The check is in the wrong place, the file extension has already been appended so ofc it won't be a valid dir.

I removed the check as it isn't strictly necessary since it only returns false without any extra error info to the user.

@jusakurai  now the function will work again if you get latest from git.

This will be fixed in the next release.

♥

Rama
