### ISSUE TITLE
No compatible with ue4.13

### ISSUE THREAD

**Issue by saidmoya12** [EverNewJoy/VictoryPlugin#7]
Now VictoryPlugin isn't compatible with the latest version of UE4

This version have some improvements for vr so will be great if could fix it

**Comment by EverNewJoy** [comment]
4.13 is a preview build, I've not yet been able to obtain it from the epic launcher, when I can get the launcher to download it it than I can check it out.

**Comment by ThomasMcVay** [comment]
There are only 2 issues preventing compile, one is a reference to WinRT in OperatingSystem__GetCurrentPlatform I can't find any mention of it in the release notes, but I imagine Epic has completely abandoned WinRT support because Microsoft has now officially abandoned it.


The second issue is with the findSource function. It appears WaveInstanceSourceMap was made a private member in FAudio device for 4.13. I don't quite understand what happened though because according to the log this change happened in february

[https://github.com/EpicGames/UnrealEngine/blame/release/Engine/Source/Runtime/Engine/Public/AudioDevice.h](https://github.com/EpicGames/UnrealEngine/blame/release/Engine/Source/Runtime/Engine/Public/AudioDevice.h)

I don't have a fix for this, but in any event, I was able to get Victory to compile simply by commenting the function out. This should compile if you need to use 4.13 immediately

[https://github.com/ThomasMcVay/VictoryPlugin/tree/413Bandaid](url)

**Comment by EverNewJoy** [comment]
ahh thanks, yes I forgot to update the github to my latest, 1 moment :)

**Comment by ThomasMcVay** [comment]
Your new commit compiled just fine, working great. Thanks.

**Comment by EverNewJoy** [comment]
Yay!

Rama

**Comment by zebratrain** [comment]
Hi Rama, 

I'm getting an error trying to implement into 4.13 - the "plugin missing or incompatible" pop-up box followed by this pop-up: 
![plugin failed](https://cloud.githubusercontent.com/assets/5498886/18527478/f75f2b7e-7a92-11e6-8dfd-14c9f80592ce.PNG)

Is there something I'm missing?
